language: ruby
rvm:
  - 2.2
  - 2.3
gemfile:
  - gemfiles/rspec_3.0_ar_4.0.gemfile
  - gemfiles/rspec_3.0_ar_4.2.gemfile
  - gemfiles/rspec_3.0_ar_5.0.gemfile
  - gemfiles/rspec_3.5_ar_4.0.gemfile
  - gemfiles/rspec_3.5_ar_4.2.gemfile
  - gemfiles/rspec_3.5_ar_5.0.gemfile
  - gemfiles/rspec_3.5_ar_edge.gemfile
matrix:
  allow_failures:
    - gemfile: gemfiles/rspec_3.5_ar_edge.gemfile
bundler_args: --without development
